create database pruebas;
use pruebas;

create table carga(
CÓDIGO INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE CHAR (30),
CIUDAD CHAR (30),
TELÉFONO CHAR (30),
CORREO CHAR (30));
LOAD DATA INFILE 'D:/DATOS.TXT' 
INTO TABLE carga FIELDS TERMINATED BY';' 
LINES TERMINATED BY'\n' IGNORE 1 LINES;

SELECT * FROM CARGA;

SELECT * FROM CARGA
INTO OUTFILE 'D:/CLIENTES.TXT' 
FIELDS TERMINATED BY '\t';

SET SQL_SAFE_UPDATES=0;
DROP TABLE CARGA;

DELETE FROM CARGA WHERE CIUDAD<>'MADRID';

UPDATE CARGA SET CIUDAD = 'GETAFE' WHERE CÓDIGO = 2;
TRUNCATE CARGA; /*BORRA EL CONTENIDO DE LA TABLA Y REINICIALIZA LOS CONTADORES*/