create table cargadificil(
CÓDIGO INT PRIMARY KEY AUTO_INCREMENT,
ERRORES VARCHAR(25),
NOMBRE VARCHAR(25),
EDAD VARCHAR(25),
ID VARCHAR(25),
CIUDAD VARCHAR(25));
LOAD DATA INFILE 'D:/DATOSEJ.TXT' 
INTO TABLE cargadificil FIELDS TERMINATED BY';' 
LINES TERMINATED BY'\n';
SELECT * FROM CARGADIFICIL;
TRUNCATE CARGADIFICIL;

UPDATE CARGADIFICIL SET CIUDAD=ID WHERE CÓDIGO='2';
UPDATE CARGADIFICIL SET ID=EDAD WHERE CÓDIGO='2';
UPDATE CARGADIFICIL SET EDAD=NOMBRE WHERE CÓDIGO='2';
UPDATE CARGADIFICIL SET NOMBRE=ERRORES WHERE CÓDIGO='2';
UPDATE CARGADIFICIL SET ERRORES='';