use jardinería;
/*1. LISTADO DE TODOS LOS CLIENTES ESPAÑOLES DE LA BD DE JARDINERÍA */
SELECT * FROM CLIENTES;
SELECT NOMBRECLIENTE AS CLIENTE, PAIS 
FROM CLIENTES 
WHERE UCASE(RTRIM(LTRIM(PAIS='España' or PAIS='Spain')));
SET SQL_SAFE_UPDATES =0;
UPDATE CLIENTES SET PAIS='España' WHERE UCASE(Pais='Spain');
/*2. NÚMERO DE PEDIDOS SEGÚN ESTADO DE PEDIDO */
SELECT * FROM PEDIDOS;
SELECT  concat(ucase(left(ESTADO,1)), substring(ESTADO FROM 2)) as Estado, COUNT(CodigoPedido)AS Cantidad FROM PEDIDOS GROUP BY Estado HAVING Estado <>'Pediente'; /* EXCLUSION DE PEDIENTE */
UPDATE PEDIDOS SET Estado='Pendiente' WHERE Estado='Pediente'; /* ELIMINACIÓN DE PEDIENTE */
/*3. NÚMERO DE PEDIDOS POR CÓDIGO DE CLIENTE */
SELECT * FROM PEDIDOS;
SELECT CodigoCliente as Codigo_de_Cliente, COUNT(*) AS Cantidad FROM PEDIDOS GROUP BY CODIGOCLIENTE;
/*3.1 NÚMERO DE PEDIDOS POR CÓDIGO DE CLIENTE DE LOS PEDIDOS REALIZADOS EN 2008 */
SELECT * FROM PEDIDOS;
SELECT YEAR(FECHAPEDIDO) AS Año ,CODIGOCLIENTE as Codigo_de_Cliente, COUNT(*) AS Cantidad FROM PEDIDOS WHERE YEAR(FECHAPEDIDO)=2008 GROUP BY FECHAPEDIDO;
/*4. LISTADO DE LOS PEDIDOS QUE SE HAN ENTREGADO EN ENERO DE CUALQUIER AÑO */
SELECT * FROM PEDIDOS;
SELECT Estado,FECHAENTREGA,CODIGOCLIENTE, COUNT(*) FROM PEDIDOS WHERE ESTADO='Entregado' GROUP BY FECHAENTREGA HAVING MONTH(FECHAENTREGA)=1;
/*5. PAGOS REALIZADOS POR PAYPAL EN 2008 Y ORDENADOS DE MAYOR A MENOR */
SELECT * FROM PAGOS;
SELECT YEAR(FECHAPAGO) AS AÑO,CANTIDAD,FORMAPAGO FROM PAGOS WHERE UCASE(RTRIM(LTRIM(FORMAPAGO='PAYPAL'))) AND year(FECHAPAGO)=2008 ORDER BY CANTIDAD DESC;
/*6. LISTADO DE CLIENTES QUE NO HAN REALIZADO NINGÚN PAGO */
SELECT * FROM CLIENTES WHERE CODIGOCLIENTE NOT IN(SELECT CODIGOCLIENTE FROM PAGOS);
/* EOF */