create table FACTURAS(
NUM_FACUTRA INT PRIMARY KEY AUTO_INCREMENT,
CODUSU INT NOT NULL,
REF_VENTA VARCHAR(20) NOT NULL UNIQUE,
FECHA_VENTA DATE NOT NULL,
SUBTOTAL DOUBLE NOT NULL,
IVA DOUBLE NOT NULL,
TOTAL DOUBLE NOT NULL,
FOREIGN KEY (CODUSU) REFERENCES VENTAS(CODUSU),
FOREIGN KEY (REF_VENTA) REFERENCES VENTAS(REF),
FOREIGN KEY (FECHA_VENTA) REFERENCES VENTAS(FECHA));