/* CONSULTAS DE MÚLTIPLES TABLAS CON INNER JOIN */
USE JARDINERÍA;

SELECT * FROM EMPLEADOS;
SELECT * FROM OFICINAS;
SELECT * FROM PEDIDOS;

SELECT * FROM EMPLEADOS INNER JOIN OFICINAS ON EMPLEADOS.CODIGOOFICINA=OFICINAS.CODIGOOFICINA;

SELECT NOMBRE, APELLIDO1, APELLIDO2 , CIUDAD, PAIS , CODIGOPOSTAL FROM EMPLEADOS
INNER JOIN OFICINAS ON EMPLEADOS.CODIGOOFICINA=OFICINAS.CODIGOOFICINA;

SELECT NOMBRE, APELLIDO1, APELLIDO2 , CIUDAD, PAIS , CODIGOPOSTAL FROM EMPLEADOS
INNER JOIN OFICINAS ON EMPLEADOS.CODIGOOFICINA=OFICINAS.CODIGOOFICINA WHERE PAIS ='ESPAÑA';

SELECT PAIS,CIUDAD, COUNT(*) FROM EMPLEADOS 
INNER JOIN OFICINAS ON EMPLEADOS.CODIGOOFICINA=OFICINAS.CODIGOOFICINA GROUP BY PAIS;

SELECT PAIS,CIUDAD, COUNT(*) FROM EMPLEADOS 
INNER JOIN OFICINAS ON EMPLEADOS.CODIGOOFICINA=OFICINAS.CODIGOOFICINA GROUP BY CIUDAD;

SELECT * FROM CLIENTES;
SELECT * FROM PEDIDOS;
SELECT * FROM DETALLEPEDIDOS;
SELECT * FROM GAMASPRODUCTOS;

/* CUANDO UNA TABLA CONTIENE CAMPOS DE DOS TABLAS DEBE IR EN EL MEDIO PARA PODER ACOPLARLE DOS INNER JOIN, UNO POR DELANTE Y OTRO POR DETRÁS */

SELECT NOMBRECLIENTE, LINEADIRECCION1, PAIS, CIUDAD, ESTADO, CODIGOPRODUCTO, CANTIDAD, PRECIOUNIDAD, ROUND((CANTIDAD * PRECIOUNIDAD)*1.21,2) AS PVPTOTAL FROM CLIENTES 
INNER JOIN PEDIDOS ON CLIENTES.CODIGOCLIENTE=PEDIDOS.CODIGOCLIENTE 
INNER JOIN DETALLEPEDIDOS ON PEDIDOS.CODIGOPEDIDO=DETALLEPEDIDOS.CODIGOPEDIDO;


SELECT NOMBRECLIENTE, LINEADIRECCION1, PAIS, CIUDAD, ESTADO, CODIGOPRODUCTO, CANTIDAD, PRECIOUNIDAD, SUM(ROUND((CANTIDAD * PRECIOUNIDAD)*1.21,2)) AS PVPTOTAL FROM CLIENTES 
INNER JOIN PEDIDOS ON CLIENTES.CODIGOCLIENTE=PEDIDOS.CODIGOCLIENTE 
INNER JOIN DETALLEPEDIDOS ON PEDIDOS.CODIGOPEDIDO=DETALLEPEDIDOS.CODIGOPEDIDO
WHERE PAIS='USA';

SELECT NOMBRECLIENTE, LINEADIRECCION1, PAIS, CIUDAD, ESTADO, CODIGOPRODUCTO, CANTIDAD, PRECIOUNIDAD, SUM(ROUND((CANTIDAD * PRECIOUNIDAD)*1.21,2)) AS PVPTOTAL FROM CLIENTES 
INNER JOIN PEDIDOS ON CLIENTES.CODIGOCLIENTE=PEDIDOS.CODIGOCLIENTE 
INNER JOIN DETALLEPEDIDOS ON PEDIDOS.CODIGOPEDIDO=DETALLEPEDIDOS.CODIGOPEDIDO
GROUP BY PAIS;

SELECT NOMBRECLIENTE, LINEADIRECCION1, PAIS, CIUDAD, ESTADO, CODIGOPRODUCTO, CANTIDAD, PRECIOUNIDAD, SUM(ROUND((CANTIDAD * PRECIOUNIDAD)*1.21,2)) AS PVPTOTAL FROM CLIENTES 
INNER JOIN PEDIDOS ON CLIENTES.CODIGOCLIENTE=PEDIDOS.CODIGOCLIENTE 
INNER JOIN DETALLEPEDIDOS ON PEDIDOS.CODIGOPEDIDO=DETALLEPEDIDOS.CODIGOPEDIDO
GROUP BY PAIS, NOMBRECLIENTE;

SELECT NOMBRECLIENTE, LINEADIRECCION1, PAIS, CIUDAD, ESTADO, CODIGOPRODUCTO, CANTIDAD, PRECIOUNIDAD, AVG(ROUND((CANTIDAD * PRECIOUNIDAD)*1.21,2)) AS PVPTOTAL FROM CLIENTES 
INNER JOIN PEDIDOS ON CLIENTES.CODIGOCLIENTE=PEDIDOS.CODIGOCLIENTE 
INNER JOIN DETALLEPEDIDOS ON PEDIDOS.CODIGOPEDIDO=DETALLEPEDIDOS.CODIGOPEDIDO
GROUP BY PAIS, NOMBRECLIENTE;
/* 1. CANTIDAD PRODUCTOS VENDIDOS DE CADA GAMA */
SELECT * FROM DETALLEPEDIDOS;
SELECT * FROM PRODUCTOS;
SELECT * FROM GAMASPRODUCTOS;

SELECT PRODUCTOS.GAMA, CANTIDAD FROM DETALLEPEDIDOS 
INNER JOIN PRODUCTOS ON DETALLEPEDIDOS.CODIGOPRODUCTO = PRODUCTOS.CODIGOPRODUCTO 
INNER JOIN GAMASPRODUCTOS ON PRODUCTOS.GAMA=GAMASPRODUCTOS.GAMA GROUP BY GAMA;

/* right y left join */
select * from empleados;

SELECT nombrecliente, codigopedido
FROM CLIENTES RIGHT JOIN PEDIDOS ON CLIENTES.CODIGOCLIENTE=PEDIDOS.CODIGOCLIENTE;

SELECT nombrecliente, codigopedido
FROM CLIENTES LEFT JOIN PEDIDOS ON CLIENTES.CODIGOCLIENTE=PEDIDOS.CODIGOCLIENTE;

SELECT * from productos;
SELECT * from gamasproductos;
SELECT * from detallepedidos;
SELECT * from pedidos;
SELECT * from clientes;
SELECT * from empleados;
SELECT * from oficina;

SELECT oficinas.PAIS, oficinas.CIUDAD, gamasproductos.GAMA, count(*) from gamasproductos inner join productos on gamasproductos.gama = productos.gama
inner join detallepedidos on productos.codigoproducto = detallepedidos.codigoproducto
inner join pedidos on detallepedidos.codigopedido= pedidos.CodigoPedido
inner join clientes on clientes.codigocliente = pedidos.codigocliente
inner join empleados on clientes.codigoempleadorepventas=empleados.codigoempleado
inner join oficinas on empleados.codigooficina = oficinas.codigooficina
WHERE oficinas.pais = "España"
GROUP BY oficinas.PAIS, oficinas.CIUDAD, gamasproductos.GAMA;