CREATE DATABASE PRUEBA;
USE PRUEBA;

/* FUNCIONES ALMACENADAS DE SQL*/

SELECT USER();
SELECT SYSDATE();
SELECT DATABASE();
SELECT VERSION();

SELECT USER(),DATABASE();

SELECT ABS(-100),PI(),CHAR(64);
SELECT CHAR(15);
SELECT BIN(2015);
SELECT HEX(100);
SELECT ROUND(SQRT(50),2);
SELECT MOD(10,2);

/* FUNCIONES MATEMÁTICAS */

SELECT ROUND((17+8)/3,1) AS CALCULO;
SELECT 17 DIV 2 AS DIVISION_ENTERA, 17 MOD 2 AS MODULO;
SELECT (4+2)<(5+6); /*True-1 False-0*/

/*OPERACIONES CON FECHAS*/

SELECT DATE_ADD('2023-09-29', INTERVAL 8 DAY);
/*
INTERVAL 10 YEAR;
INTERVAL 10 MONTH;
INTERVAL 10 DAY;
*/

SELECT ROUND(DATEDIFF(NOW(),'1999-08-08')/365);
SELECT DATEDIFF(NOW(),'1964-10-05');
SELECT HEX('ÁLVARO');

/* FUNCIONES UTILES */

SELECT UCASE('álvaro');
SELECT LCASE('ÁLVARO');

SELECT length('ÁLVARO LOZANO GARCÍA')-2 AS LONGITUD;

/*FUNCIONES DE FECHAS Y HORAS*/

SELECT CURDATE();
SELECT CURTIME();

SELECT dayofyear(NOW());
SELECT dayofweek(NOW());
SELECT dayofmonth(NOW());
SELECT dayname(NOW());
SELECT weekofyear(NOW());
SELECT week(now());

/*FUNCIONES DE  TEXTO*/

SELECT CONCAT('Hola,',' colegui',' Paco');
SELECT CONCAT_WS('-','A','121212','TA');

SELECT LEFT('francisco',3);
SELECT RIGHT('francisco',4);
SELECT SUBSTRING('francisco',4,3); /*El primer número define desde que posicion se debe extraer
el string, el segundo número define cuántas letras se quieren en el string*/

SELECT CONCAT('Pedro',SPACE(20),'SANCHEZ');

SELECT REVERSE('ROMA');
SELECT REPEAT('TOMA ',3);
SELECT REPLACE('PACO','AC','OTORR');
/*EJERCICIO INICIALES Y USARIO*/
SELECT LEFT('alvaro',1) AS NOM;
SELECT LEFT('lozano',1) AS AP1;
SELECT LEFT('garcía',1) AS AP2;
SELECT UCASE(CONCAT(left('álvaro ',1),left('lozano',1),left('garcía',1),'-',year(now())))AS INICIALES;
