CREATE TABLE USUARIOS(
	COD INTEGER PRIMARY KEY AUTO_INCREMENT,
	NOMBRE_USUARIO VARCHAR(150) NOT NULL UNIQUE,
	CONTRASEÑA VARCHAR(255) NOT NULL,
	NOMBRE_CLIENTE VARCHAR(100) NOT NULL,
	APEL1 VARCHAR(100) NOT NULL,
	APEL2 VARCHAR(100) NOT NULL,
	TLF VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(150) NOT NULL,
	DIRECCION VARCHAR(200) NOT NULL,
	CIUDAD VARCHAR(50) NOT NULL,
	CP VARCHAR(10) NOT NULL
);
CALL insertar_usuarios("A","A","A","A","A","A","A","A","A","A");
CALL MODIFICAR_DATOS(1,"C","C","B","B","Z","Z","Y","Y","U","U");
TRUNCATE TABLE USUARIOS;
SELECT * FROM USUARIOS;
CREATE TABLE PRODUCTOS(
    COD INT PRIMARY KEY AUTO_INCREMENT,
    MODELO VARCHAR(100) NOT NULL UNIQUE,
    MARCA VARCHAR(50) NOT NULL,
    DESCRIPCION MEDIUMTEXT,
    PRECIO DOUBLE NOT NULL,
    STOCK INT NOT NULL,
    GENERO ENUM("HOMBRE","MUJER","NIÑO/A") NOT NULL
);

CREATE TABLE VENTAS(
REF INT PRIMARY KEY,
CODUSU INT NOT NULL,
CODPRO INT NOT NULL,
FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
METODOPAGO ENUM("TARJETA","PAYPAL","CONTRAREMBOLSO")
);
INSERT INTO VENTAS(REF,CODUSU,CODPRO,METODOPAGO)VALUES(1,1,1,"TARJETA");
CREATE TABLE FACTURAS(
NUM_FACUTRA INT PRIMARY KEY AUTO_INCREMENT,
CODUSU INT NOT NULL,
REF_VENTA INT NOT NULL UNIQUE,
FECHA_VENTA DATE NOT NULL,
SUBTOTAL DOUBLE NOT NULL,
IVA DOUBLE NOT NULL,
TOTAL DOUBLE NOT NULL,
METODOPAGO ENUM("TARJETA","PAYPAL","CONTRAREMBOLSO")
);
select * from ventas;
call GENERAR_FACTURA(1);
CREATE TABLE ENVIOS(
COD INT PRIMARY KEY AUTO_INCREMENT,
CODUSU INT NOT NULL,
REFVENTA VARCHAR(20) NOT NULL UNIQUE,
FSALIDA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FESTIMADA DATE,
FENTREGA DATE,
DIRECCION VARCHAR(200) NOT NULL,
CIUDAD VARCHAR(50) NOT NULL,
CP VARCHAR(10) NOT NULL
);

CREATE TABLE CARRITO(
CODUSU INT NOT NULL,
CODPRO INT NOT NULL,
PRECIO DOUBLE NOT NULL
);

CREATE TABLE IMÁGENES(
CODPRO INT NOT NULL,
URL VARCHAR(200)
);