create database TAREA;
create table FACTURAS(
COD INT primary key auto_increment,
NUMF INT, /*funct NUMFACTU()- F1(COD)/2024(FECHA)*/
EMISOR VARCHAR(50), /*funct EMIFACTU()- PEDORRI CLUB C/LEON,66 MADRID 28050*/
CLIENTE VARCHAR(50),
BI DOUBLE,/*BASE IMPONIBLE*/
IVA  DOUBLE, /*4%/10%/21%*/
CONSTRAINT CHK_IVA CHECK (0.04 OR 0.1 OR 0.21),
CUOTA DOUBLE, /*funct CALCUOTA()- BI+IVA*/
TPAGAR DOUBLE);
create table PEDIDOS(
COD INT primary key auto_increment,
PEDIDO VARCHAR(10), /*funct CODPED()- C-1(COD)*/
PRODUCTO varchar(50),
CANTIDAD INT,
PRECIOUNI DOUBLE,
IMPORTE DOUBLE/*funct IMPPEDIDO()- CANITDAD*PRECIOUNI  */);
INSERT INTO facturas VALUES();
INSERT INTO pedidos VALUES();