create database Basededatos16_11_2023;
USE Basededatos16_11_2023;
create table IF NOT EXISTS CLIENTES(
codigo INT primary key auto_increment,
nombre VARCHAR (50),
ciudad VARCHAR (50),
credito DOUBLE,
fechaalta DATE);
create table IF NOT EXISTS VENTAS(
codcli INT,
codpro INT,
cantidad INT(9),
pago CHAR(2));
create table IF NOT EXISTS PRODUCTOS(
codigo INT PRIMARY KEY auto_increment,
descripcion mediumtext,
categoria INT,
precio DOUBLE,
origen VARCHAR(30));
INSERT INTO CLIENTES(NOMBRE, CIUDAD,CREDITO,FECHAALTA) VALUES("Pepisa","Getafe",2000,"2020-10-1"),
("Arka","Leganes",1000,"2022-2-14"),
("Calamosa","Fuenlabrada",500,"2022-3-15"),
("FUTURE","Getafe",1000,"2023-5-20"),
("Cayosa","Fuenlabrada",8000,"2023-1-1"),
("Tulipa","Leganés",5000,"2021-1-10"),
("Curcuma","Fuenlabrada",1000,"2020-6-6"),
("Tipin","Getafe",2000,"2019-1-1"),
("Torete","Getafe",500,"2023-10-1");
select * from clientes;
select * from PRODUCTOS;
select * from VENTAS;
drop table clientes;
INSERT INTO ventas(CODCLI, CODPRO,CANTIDAD,PAGO) VALUES(2,3,4,"SI"),(1,2,1,""),(3,1,5,"SI"),(4,2,6,"SI"),(5,3,10,""),(6,1,7,"SI"),(3,4,3,""),(7,5,12,"SI");
INSERT INTO productos(DESCRIPCION,CATEGORIA,PRECIO,ORIGEN) VALUES("TURRÓN",1,20,"XIXONA"),
("MAZAPÁN",3,15,"ESTEPA"),
("ROSCÓN",2,25,"MADRID"),
("FRUTA ESCARCHADA",2,50,"AVILA"),
("FERRERO",1,60,"MADRID"),
("PASAS",1,10,"PERU"),
("FERRERO",2,50,"PADUA");
/*IMPORTE TOTAL VENDIDO*/
select * from clientes;
select * from PRODUCTOS;
select * from VENTAS;
SELECT SUM(PRODUCTOS.PRECIO*VENTAS.CANTIDAD)AS TOTAL_VENDIDO FROM PRODUCTOS INNER JOIN VENTAS ON PRODUCTOS.CODIGO=VENTAS.CODPRO;
/* CANTIDAD DE PRODUCTOS POR CLIENTE E IMPORTE */
SELECT CODCLI, VENTAS.CANTIDAD, PRODUCTOS.PRECIO*VENTAS.CANTIDAD AS IMPORTETOTALCLIENTE FROM PRODUCTOS INNER JOIN VENTAS ON PRODUCTOS.CODIGO=VENTAS.CODPRO INNER JOIN CLIENTES ON VENTAS.CODCLI=CLIENTES.CODIGO  GROUP BY CODCLI;
/* TOTAL DE CREDITO DE LOS CLIENTES QUE NO HAN COMRPADO NADA */
SELECT PAGO,CLIENTES.CODIGO,SUM(CLIENTES.CREDITO) FROM PRODUCTOS INNER JOIN VENTAS ON PRODUCTOS.CODIGO=VENTAS.CODPRO INNER JOIN CLIENTES ON VENTAS.CODCLI=CLIENTES.CODIGO  GROUP BY PAGO;