SELECT * FROM GAMASPRODUCTOS;
SELECT * FROM PAGOS;
SELECT * FROM EMPLEADOS;

SELECT DISTINCT(FormaPago) FROM PAGOS;
SELECT COUNT(*) FROM EMPLEADOS;
SELECT (CONCAT(Nombre, Apellido1, Apellido2)) AS NombreCompleto FROM EMPLEADOS;
SELECT COUNT(DISTINCT(CONCAT(Nombre, Apellido1, Apellido2))) AS NumeroDeEmpleadosUnicos FROM EMPLEADOS;

SELECT*FROM PEDIDOS;
SELECT COUNT(*) FROM PEDIDOS;
SELECT COUNT(FechaEntrega) FROM PEDIDOS;

SELECT ESTADO,COUNT(*) FROM PEDIDOS GROUP BY ESTADO;
SELECT ESTADO,COUNT(*) FROM PEDIDOS GROUP BY ESTADO HAVING ESTADO <> 'PEDIENTE';

SELECT CODIGOOFICINA,COUNT(*) FROM EMPLEADOS GROUP BY CODIGOOFICINA;
SELECT RIGHT(CODIGOOFICINA,2) AS PAIS, COUNT(*) FROM EMPLEADOS GROUP BY PAIS;
SELECT LEFT(CODIGOOFICINA,3) AS PAIS, COUNT(*) FROM EMPLEADOS GROUP BY PAIS;

SELECT CodigoCliente AS Cliente,COUNT(*) as NumeroDePedidos FROM PEDIDOS GROUP BY CodigoCliente;
SELECT CodigoCliente AS Cliente,COUNT(*) as NumeroDePedidos FROM PEDIDOS where estado ='entregado' group by CODIGOCLIENTE asc;
SELECT CodigoCliente AS Cliente,COUNT(*) as NumeroDePedidos FROM PEDIDOS where estado <>'entregado' group by CODIGOCLIENTE desc;

SELECT * FROM CLIENTES WHERE CODIGOCLIENTE NOT IN(SELECT CodigoCLIENTE FROM PEDIDOS);

CREATE TABLE PEDIDOS_ENTREGADOS SELECT * FROM  PEDIDOS WHERE ESTADO='entregado';
select * from pedidos_entregados;