/*
$ - FINAL DE CADENA
^ - INICIO DE CADENA
[] - CARACTER DE BUSQUEDA
. - CARACTER CUALQUIERA
+ - UNA O MAS VECES
? - NINGUNA O UNA
* - NINGUNA O MAS
*/
USE JARDINERIA;
SELECT * FROM JARDINERIA WHERE NOMBRE REGEXP '^[A-Z]?[0-9]{8}[A-Z]{1}$';
SELECT * FROM JUGADORES WHERE PROCEDENCIA RLIKE '';/*MANERA ALTERNATIVA DE ESCRIBIR REGEXP*/