CREATE DATABASE FORMACION;
USE FORMACION;

CREATE TABLE IF NOT EXISTS CURSOS(
	CODIGO INT PRIMARY KEY AUTO_INCREMENT,/*LAS PRIMARY KEY SON UN CAMPO INDEXADO ÚNICO PRIMARIO
    QUE SE ENCUENTRA CON MAYOR FACILIDAD QUE OTROS CAMPOS*/
    NOMBRE VARCHAR(100) NOT NULL COMMENT 'DESCRIPCIÓN DEL CURSO',
    FAMILIA ENUM('TIC','COMERCIO','MARKETING') NOT NULL,
    MATERIA VARCHAR(50),
    FINICIO DATE NOT NULL,
    FFIN DATE, 
    HORAS INTEGER,
    OBSERVACIONES MEDIUMTEXT /*AL SER EL ULTIMO CAMPO NO HACE FALTA CERRARLO CON COMA O PUNTO Y COMA*/
);
CREATE TABLE IF NOT EXISTS ALUMNOS(
	CODIGO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR (30) NOT NULL,
    APEL1 VARCHAR(30) NOT NULL,
    APEL2 VARCHAR(30),
    FNACI DATE NOT NULL,
    FALTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TLF VARCHAR(15) NOT NULL UNIQUE,
    NIF VARCHAR(13) NOT NULL UNIQUE,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    NIVELACADEMICO VARCHAR(50),
    CIUDAD VARCHAR(100),
    OBSERVACIONES MEDIUMTEXT
);
ALTER TABLE ALUMNOS ADD COLUMN OBSERVACIONES MEDIUMTEXT; /*ESTE COMANDO AÑADIRÍA A LA TABLA YA CREADA 
EL CAMPO OBSERVACIONES SIN TENER QUE BORRAR LA TABLA ENTERA PARA AÑADIR EL CAMPO*/
DROP TABLE ALUMNOS;/*EJECUTAR ESTA LINEA ELIMINARÍA LA TABLA QUE HEMOS GENERADO ARRIBA*/
DESCRIBE ALUMNOS;

INSERT INTO ALUMNOS (NOMBRE,APEL1,APEL2,FNACI,TLF,NIF,EMAIL,NIVELACADEMICO,CIUDAD) VALUES 
('ANDRÉSJ','LÓPEZ','PÉREZ','1987-05-12','+34686665623','66666666X','satanteama@infernal.com','estratosférico','Madrid'),
('ANDRÉS','LÓPEZ','PAREZ','1987-05-02','+34686665923','66666566X','satanteama@infernl.com','estratosféro','Madra'),
('ANA','PÉREZ','REVERTE','1997-05-01','+34111111112','11111112C','caminemosconelseñor@laluzteilumina.com','elevado','Madrid');
select*from ALUMNOS; /*MUESTRA LOS DATOS INTRODUCIDOS EN LA TABLA*/

SELECT CODIGO,NOMBRE,APEL1,APEL2, CONCAT(LEFT(NOMBRE,1), LEFT(APEL1,1),LEFT(APEL2,1)) AS INICIALES FROM ALUMNOS WHERE CIUDAD='MADRID';
SELECT NOMBRE, DAY(FNACI), MONTH(FNACI), YEAR(FNACI) AS ANO, CONCAT_WS('-',DAY(FNACI),MONTH(FNACI),YEAR(FNACI))AS FECHAESP FROM ALUMNOS;
/*USUARIO: 3 PRIMERAS LETRAS CIUDAD, DIA Y MES DE ALTA
CORREO: 3 PRIMERAS LETRAS DEL NOMBRE, UN PUNTO, EL SEGUNDO APELLIDO Y @AMBARSOLUTIONS.COM*/
SELECT NOMBRE, concat(LEFT(CIUDAD,3),(DAY(FALTA)),(MONTH(FALTA)),LEFT(APEL2,3)) AS USUARIO,concat(LEFT(NOMBRE,3),'.',(APEL2),'@AMBARSOLUTIONS.COM') AS CORREO FROM ALUMNOS;
/*Es NECESARIO utilizar LEFT en las extracciones de strings*/