CREATE DATABASE BIBLIOTECA;
USE BIBLIOTECA;

CREATE TABLE USUARIOS(
	CODIGO INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDOS VARCHAR(100) NOT NULL,
    FNACI DATE NOT NULL,
    TLF VARCHAR(20),
    DIR VARCHAR(50),
    OBSERV MEDIUMTEXT
);

CREATE TABLE LIBROS(
	CODIGO INTEGER PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR (100) NOT NULL,
    GENERO ENUM('FICCIÓN','ROMÁNTICA','POLICÍACA','HISTÓRICA','POB'),
    ISBN VARCHAR(15) NOT NULL,
    AUTOR INTEGER,
    PAG INTEGER COMMENT 'Número de páginas totales del libro',
    FENTRADA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    RESUMEN MEDIUMTEXT,
    FOREIGN KEY (AUTOR) REFERENCES AUTORES(COD)
);
CREATE TABLE AUTORES(
COD INTEGER PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(150) NOT NULL,
NACIONALIDAD VARCHAR(50),
PAIS VARCHAR(50),
NACIMIENTO DATE
);
CREATE TABLE PRESTAMOS(
CODUSU INTEGER NOT NULL,
CODLIB INTEGER NOT NULL,
FPREST TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FENTREGA DATE,
DIASPEN INTEGER,
FOREIGN KEY (CODUSU) REFERENCES USUARIOS(CODIGO)
ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY (CODLIB) REFERENCES LIBROS (CODIGO)
ON UPDATE CASCADE ON DELETE CASCADE
);
INSERT INTO USUARIOS (NOMBRE, APELLIDOS, FNACI, TLF, DIR)VALUES
('ANDRES','TORRES MÁLAGA','1987-05-12','666353265','C/ MIRLO BLANCO 14, 3ºA'),
('CARMEN','SÁNCHEZ','2003-02-08','666353265','C/ ARTURO SORIA, 5 3ºA'),
('IVÁN','ELVIRA BARBUDO','2005-01-16','666353265','C/ SALAMANCA, 10');
SELECT*FROM USUARIOS;
INSERT INTO LIBROS (TITULO,GENERO, ISBN, PAG)VALUES
('MOMO','FICCIÓN','545654556N',150),
('EL HOBBIT','FICCIÓN','545656456N',340),
('GUERRA Y PAZ','HISTÓRICA','545656456N',2000);

SELECT*FROM LIBROS;

INSERT INTO PRESTAMOS (CODUSU, CODLIB) VALUES
(1,3),
(1,2),
(3,3),
(3,1);

SELECT*FROM PRESTAMOS;

SELECT * FROM USUARIOS NATURAL JOIN PRESTAMOS NATURAL JOIN LIBROS;