create table gente(
CODIGO INT PRIMARY KEY auto_increment,
FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
NOMBRE VARCHAR(50));
SELECT * FROM GENTE;
/*COMANDOS TCL*/
SET AUTOCOMMIT = 0;
START TRANSACTION;
BEGIN; /* TAMBIEN PUEDE PONERSE BEGIN WORK, ES LO MISMO*/
INSERT INTO GENTE(NOMBRE) VALUES('Álvaro'),('Andrés el cagón'),('Sergio el canarión');
rollback; /* DESHACER HASTA EL ANTERIOR COMMIT */
commit; /* CONSOLIDACIÓN DE LO HECHO HASTA EL MOMENTO */
truncate table gente; /* se conserva el cambio a pesar del rollback porque los comandos DML y DDL no se pueden deshacer */
SET SQL_SAFE_UPDATES = 0;
delete from gente where nombre='Andrés el cagón';
SAVEPOINT TRIO; /* PUNTO DE GUARDADO ENTRE COMMITS, UNA VEZ SE HACE ROLLBACK O COMMIT DESAPARECE*/
ROLLBACK TO TRIO; 
/* -----------------------PRACTICA----------------------- */
INSERT INTO GENTE(NOMBRE) VALUES('Álvaro'),('Andrés el cagón'),('Sergio el canarión'),('Paco'),('Pepe');
SELECT * FROM GENTE;
SAVEPOINT INSERCION;
SET SQL_SAFE_UPDATES = 0;
UPDATE GENTE SET NOMBRE='Nuevo' WHERE NOMBRE='Pepe';
UPDATE GENTE SET NOMBRE='PacoDistinto' WHERE NOMBRE='Paco';
rollback TO INSERCION;
SELECT * FROM GENTE;
SAVEPOINT ACTUALIZACION;
DELETE FROM GENTE WHERE NOMBRE='Álvaro'||NOMBRE='PacoDistinto'||NOMBRE='Nuevo';
SELECT * FROM GENTE;
rollback TO ACTUALIZACION;
SET AUTOCOMMIT = 1;
SET SQL_SAFE_UPDATES = 1;
/* DCL (DATA CONTROL LANGUAGE) USUARIOS Y PERMISOS */
SELECT USER(); /* MUESTRA EL USUARIO CON EL QUE SE ESTA ACCEDIENDO A SQL */
CREATE USER PEPE IDENTIFIED BY '1234'; /* CREA UN USUARIO DE LA BASE DE DATOS LLAMADO PEPE QUE COMO CONTRASEÑA TIENE '1234'*/
DROP USER PEPE; /* BORRARÍA EL USUSARIO PEPE, NO HACE FALTA CONTRASEÑA PORQUE ESTAMOS ACCEDIENDO DESDE ROOT */
GRANT ALL PRIVILEGES ON *.* TO PEPE; /* LE DA AL USUARIO PEPE TODOS LOS PRIVILEGIOS EN TODAS LAS BASES DE DATOS (* PRIMER ASTERISCO) Y EN TODAS LAS TABLAS (* SEGUNDO ASTERISCO), EN DICHO ORDEN */
FLUSH PRIVILEGES; /* REFRESCA LOS PRIVILEGIOS DE SQL PARA QUE TENGAN EFECTO EN CASO DE QUE POR ALGUN MOTIVO TODAVÍA NO SE HAYAN ACTUALIZADO */
REVOKE INSERT ON *.* FROM PEPE;
CREATE USER PEPITA IDENTIFIED BY '1234';
GRANT SELECT, UPDATE ON PRUEBA.* TO PEPITA; /* LE DA PERMISOS DE LECTURA Y ACTUALIZACIÓN EN LA BASE DE DATOS PRUEBA, EN TODAS SUS TABLAS A PEPITA */
REVOKE UPDATE ON PRUEBA.* FROM PEPITA;
SHOW GRANTS FOR PEPITA; /* MUESTRA LOS PERMISOS CONCEDIDOS, LAS TABLAS Y LAS BASES DE DADOS EN LAS QUE SE HA CONCEDIDO ACCESO PARA UN USUARIO */
SHOW GRANTS FOR root@localhost; /* VER PRIVILEGIOS DEL USUARIO ROOT */
/* -----PRACTICA----- */

CREATE USER PEPOTE IDENTIFIED BY '1234';
GRANT SELECT, UPDATE ON basededatos16_11_2023.GENTE TO PEPOTE;
CREATE USER LAPIZCONGOMA IDENTIFIED BY '1234';
GRANT CREATE, DROP, DELETE ON *.* TO LAPIZCONGOMA;

/* USAGE (DCL) */
ALTER USER PEPITA WITH max_queries_per_hour 50; /* LIMITA EL NUMERO DE CONSULTAS DE LA BASE DE DATOS A UNA CANTIDAD POR HORA */
ALTER USER PEPITA WITH max_updates_per_hour 50; /* LIMITA EL NUMERO DE CAMBIOS EN LA BASE DE DATOS A UNA CANTIDAD POR HORA  */
