CREATE TABLE ALMACEN (
COD INT PRIMARY KEY AUTO_INCREMENT,
REF VARCHAR(10) NOT NULL,
DESRCIPCION VARCHAR(50) NOT NULL,
TIPO VARCHAR(10),
CANTIDAD INT,
FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
insert INTO ALMACEN(ref,DESRCIPCION,tipo,cantidad) values("AA2022","PIRULETAS","SALIDA",20),("asdhasd","hola","ENTRADA",5);
select * from almacen;
TRUNCATE TABLE ALMACEN;
CREATE TABLE ALMACENlog (
COD INT PRIMARY KEY AUTO_INCREMENT,
REF VARCHAR(10) NOT NULL,
DESRCIPCION VARCHAR(50) NOT NULL,
TIPO VARCHAR(10),
CANTIDAD INT,
FECHA TIMESTAMP,
USUARIO VARCHAR(100),
TIPOCAMBIO VARCHAR(1),
FECHACREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
SET SQL_SAFE_UPDATES=0;
update almacen set DESRCIPCION="CACA" where ref="AA2022";
delete from almacen where ref="asdhasd";
select * from almacenLOG;
TRUNCATE TABLE ALMACEN;